create database customer_shopping;
use customer_shopping;

SELECT * FROM customer_shopping_data;

# ------------------ Solving some business problems-----------------------
-- Q1. What is the total revenue generated by male vs. female customers?
select gender,sum(purchase_amount) as total_revenue_generated
from customer_shopping_data
group by gender;

-- Q2. Which customers used a discount but still spent more than the average purchase amount?
select * from customer_shopping_data;

SELECT customer_id, purchase_amount
FROM customer_shopping_data
WHERE discount_applied = 'Yes'
AND purchase_amount >= (
    SELECT AVG(purchase_amount) FROM customer_shopping_data
);

-- Q3. Which are the top 5 products with the highest average review rating?
select * from customer_shopping_data;

select item_purchased, avg(review_rating) as avg_review_rating
from customer_shopping_data
group by item_purchased
order by avg_review_rating desc
limit 5;

-- Q4. Compare the average Purchase Amounts between Standard and Express Shipping.
select * from customer_shopping_data;

SELECT shipping_type, AVG(purchase_amount) AS avg_purchase
FROM customer_shopping_data
WHERE shipping_type IN ('Express', 'Standard')
GROUP BY shipping_type;

-- Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.

select * from customer_shopping_data;

select subscription_status,count(*) as no_of_customers,avg(purchase_amount) as avg_spend,sum(purchase_amount) as total_spend
from customer_shopping_data
group by subscription_status;

-- Q6. Which 5 products have the highest percentage of purchases with discounts applied?
select * from customer_shopping_data;

SELECT item_purchased,
       (SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END) * 100.0 
        / COUNT(*)) AS discount_percentage
FROM customer_shopping_data
GROUP BY item_purchased
ORDER BY discount_percentage DESC
LIMIT 5;

-- Q7. Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment.

select * from customer_shopping_data;

WITH customer_type AS (
    SELECT customer_id,
           previous_purchases,
           CASE
               WHEN previous_purchases = 1 THEN 'New'
               WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
               ELSE 'Loyal'
           END AS customer_segment
    FROM customer_shopping_data
)

SELECT customer_segment,
       COUNT(*) AS Number_of_customers
FROM customer_type
GROUP BY customer_segment;

-- Q8. What are the top 3 most purchased products within each category?

select * from customer_shopping_data;

WITH item_counts AS (
    SELECT category,
           item_purchased,
           COUNT(customer_id) AS total_orders,
           ROW_NUMBER() OVER (PARTITION BY category ORDER BY COUNT(customer_id) DESC) AS item_rank
    FROM customer_shopping_data
    GROUP BY category, item_purchased
)
SELECT item_rank,category, item_purchased, total_orders
FROM item_counts
WHERE item_rank <=3;


-- Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?

SELECT subscription_status,
       COUNT(customer_id) AS repeat_buyers
FROM customer_shopping_data
WHERE previous_purchases > 5
GROUP BY subscription_status;

-- Q10. What is the revenue contribution of each age group? 
SELECT 
    age_group,
    SUM(purchase_amount) AS total_revenue
FROM customer_shopping_data
GROUP BY age_group
ORDER BY total_revenue desc;


